 ---
 - hosts: all
   become:true #For root user
   tasks:
    -name: Install apache2 httpd
    ansible.builtin.apt
    name: apache2
    state: present 
    update_cache: yes
   -name:Copy html files with owner permissions
    ansible.builtin.copy
      src: index.html
      dest: /var/www/html/
      owner: root
      group: root
      mode: '0644'



